SMODS.Atlas{
    key="duckbomb",
    path="duckbomb.png",
    px=71,
    py=95
}
SMODS.Atlas{
    key="spark",
    path="spark.png",
    px=64,
    py=64,
    center= 10,
}
SMODS.Atlas{
    key="modicon",
    path="spark.png",
    px=64,
    py=64,
}:register()
SMODS.Atlas{
    key="skull",
    path="skull.png",
    px=32,
    py=32,
}
SMODS.Atlas{
    key="theentiredeck",
    path="theentiredeck.png",
    px=71,
    py=95
}
SMODS.Atlas{
    key="achieve",
    path="achieve.png",
    px=100,
    py=100
}
SMODS.Atlas{
    key="jestersregret",
    path="jimbosregret.png",
    px=71,
    py=95
}
SMODS.Atlas{
    key="tnirpeulb",
    path="tnirpeulb.png",
    px=71,
    py=95
}
SMODS.Atlas{
    key="mrotsniarb",
    path="mrotsniarb.png",
    px=71,
    py=95
}
SMODS.Atlas{
    key="chutesandladders",
    path="slideladder.png",
    px=71,
    py=95
}
SMODS.Atlas{
    key="watermelonreactor",
    path="watermelon_reactor.png",
    px=71,
    py=95
}
SMODS.Atlas{
    key="ducky",
    path="ducky.png",
    px=71,
    py=95
}